image:
  repository: intens.azurecr.io/simsvc-mpt
  tag: latest
  pullPolicy: IfNotPresent

server:
  replicas: 1
  host: intens.test
  clusterIssuer: intens-issuer
  pwsecret: intens-pw

scheduler:
  replicas: 1

worker:
  replicas: 4
  threads: 4

work:
  storageClass: standard
  size: 5Gi
