# Simsvc chart values for deploying our chart on Virtual Kubelet/Node.

worker:
  spec:
    &vk-spec
    tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
      effect: NoSchedule
    nodeSelector:
      kubernetes.io/role: agent
      beta.kubernetes.io/os: linux
      type: virtual-kubelet
    # See https://github.com/virtual-kubelet/virtual-kubelet/issues/456
    # Needs Kubernetes 1.10 on the cluster.
    dnsPolicy: ClusterFirst
    dnsConfig:
      searches:
        - default.svc.cluster.local
        - svc.cluster.local
        - cluster.local

scheduler:
  spec: *vk-spec

# PVs are not supported by VK currently (at all, on any platform).
# https://github.com/virtual-kubelet/virtual-kubelet/issues/367.  We
# left server on a real node above, so it can mount db.  Also, kubectl
# logs -f does not work on VK pods (it does not follow, just prints
# about a dozen last lines of the current log; the full log can be
# retrieved with "az container logs" but appears unavailable via K8s).
# That is another reason for keeping the server off VK.
work:
  storageClass: ""
