apiVersion: v1
kind: Service
metadata:
  name: {{ template "simsvc.fullname" . }}-server
spec:
  selector:
    app: {{ template "simsvc.name" . }}
    release: {{ .Release.Name | quote }}
    component: server
  ports:
    - name: {{ template "simsvc.fullname" . }}-server
      port: 8080
