apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "simsvc.fullname" . }}-work
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.work.storageClass }}
  resources:
    requests:
      storage: {{ .Values.work.size }}
  selector:
    matchLabels:
      name: {{ template "simsvc.fullname" . }}-work
