debug: false
# openShift uses Route instead of Ingress.
openShift: true

image:
  repository: simsvc-mpt
  tag: latest
  # pullPolicy: IfNotPresent
  pullPolicy: Always

server:
  replicas: 1
  host: intens.rahtiapp.fi
  #whitelist of allowed IP addresses, empty for all.  Only used on OpenShift.
  whitelist: ""
  #clusterIssuer for cert-manager.  Not used on OpenShift.
  clusterIssuer: intens-issuer
  pwsecret: intens-pw
  spec: {}

scheduler:
  replicas: 1
  spec: {}

worker:
  replicas: 4
  # threads used by each worker for executing tasks (0 = detect cores)
  threads: 0
  # resources (requests & limits) for the container
  resources: {}
  spec: {}

db:
  # storageClass for db volume, "default" (don't specify) or "" (disable PV)
  storageClass: standard-rwo
  size: 5Gi

work:
  # storageClass for work volume, "default" (don't specify) or "" (disable PV)
  storageClass: default
  size: 5Gi
