image:
  repository: intens.azurecr.io/simsvc-mpt
  tag: latest
  # pullPolicy: IfNotPresent
  pullPolicy: Always

server:
  replicas: 1
  host: intens.northeurope.cloudapp.azure.com
  clusterIssuer: intens-issuer
  pwsecret: intens-pw

scheduler:
  replicas: 1

worker:
  replicas: 4
  threads: 4

work:
  storageClass: intens-work
  size: 5Gi
