debug: false

image:
  repository: intens.azurecr.io/simsvc-mpt
  tag: latest
  # pullPolicy: IfNotPresent
  pullPolicy: Always

server:
  replicas: 1
  host: intens.westeurope.cloudapp.azure.com
  clusterIssuer: intens-issuer
  pwsecret: intens-pw
  spec: {}

scheduler:
  replicas: 1
  spec: {}

worker:
  replicas: 4
  # threads used by each worker for executing tasks (0 = detect cores)
  threads: 0
  # resources (requests & limits) for the container
  resources: {}
  spec: {}

db:
  storageClass: intens-work
  size: 5Gi

work:
  storageClass: intens-work
  size: 5Gi
