debug: false
# openShift uses Route instead of Ingress.
openShift: true

image:
  repository: simsvc-mpt
  tag: latest
  pullPolicy: IfNotPresent
  # pullPolicy: Always

server:
  replicas: 1
  # host name for ingress or route.  If empty no ingress or route is defined.
  host: intens.rahtiapp.fi
  # serviceSpec is additional spec for the web service, e.g., type.
  # selector and ports come from the template; anything else can be
  # put here.
  serviceSpec: {}
  # whitelist of allowed IP addresses, empty for all.  Only used on OpenShift.
  whitelist: ""
  # clusterIssuer for cert-manager.  Not used on OpenShift.
  clusterIssuer: intens-issuer
  pwsecret: intens-pw
  # env variables appended to the pod template
  env: []
  # spec items appended to the pod template
  spec: {}

scheduler:
  replicas: 1
  spec: {}

worker:
  replicas: 4
  # threads used by each worker for executing tasks (0 = detect cores)
  threads: 0
  # resources (requests & limits) for the container
  resources: {}
  # env vars appended to the pod template
  env: []
  # spec items appended to the pod template
  spec: {}

db:
  # storageClass for db volume, "default" (don't specify) or "" (disable PV)
  storageClass: standard-rwo
  size: 5Gi

work:
  # storageClass for work volume, "default" (don't specify) or "" (disable PV)
  storageClass: default
  size: 5Gi
