{{ if .Values.db.storageClass -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "simsvc.fullname" . }}-db
spec:
  accessModes:
    - ReadWriteOnce
  {{ if ne .Values.db.storageClass "default" -}}
  storageClassName: {{ .Values.db.storageClass }}
  {{ end -}}
  resources:
    requests:
      storage: {{ .Values.db.size }}
{{ end -}}
