apiVersion: v1
kind: Service
metadata:
  name: {{ template "simsvc.fullname" . }}-scheduler
spec:
  selector:
    app: {{ template "simsvc.name" . }}
    release: {{ .Release.Name | quote }}
    component: scheduler
  ports:
    - name: scheduler
      port: 8786
    - name: web-ui
      port: 8787
