{{ if and .Values.server.host .Values.openShift -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "simsvc.fullname" . }}-route
  {{- if .Values.server.whitelist }}
  annotations:
    haproxy.router.openshift.io/ip_whitelist: {{ .Values.server.whitelist }}
  {{- end }}
spec:
  host: {{ .Values.server.host }}
  path: /{{ .Release.Name }}/
  port:
    targetPort: simsvc
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ template "simsvc.fullname" . }}-server
    weight: 100
# Workaround for an OpenAPI bug.
# https://github.com/openshift/origin/issues/24060
status:
  ingress: []
{{ end -}}
