apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "simsvc.fullname" . }}-server
  labels:
    app: {{ template "simsvc.name" . }}
    release: {{ .Release.Name | quote }}
    component: scheduler
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ template "simsvc.name" . }}
      release: {{ .Release.Name | quote }}
      component: server
  template:
    metadata:
      labels:
        app: {{ template "simsvc.name" . }}
        release: {{ .Release.Name | quote }}
        component: server
    spec:
      containers:
        - name: {{ template "simsvc.fullname" . }}-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          tty: true
          env:
            # - name: FLASK_DEBUG
            #   value: "1"
            - name: DASK_SCHEDULER_ADDRESS
              value: {{ template "simsvc.fullname" . }}-scheduler:8786
            - name: WORK_DIR
      {{- if .Values.work.storageClass }}
              value: "/work"
          volumeMounts:
            - mountPath: "/work"
              name: work
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: {{ template "simsvc.fullname" . }}-work
      {{- else }}
              value: ""
      {{- end }}
