apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "simsvc.fullname" . }}-server
  labels:
    app: {{ template "simsvc.name" . }}
    release: {{ .Release.Name | quote }}
    component: server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ template "simsvc.name" . }}
      release: {{ .Release.Name | quote }}
      component: server
  template:
    metadata:
      labels:
        app: {{ template "simsvc.name" . }}
        release: {{ .Release.Name | quote }}
        component: server
    spec:
      containers:
        - name: {{ template "simsvc.fullname" . }}-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          tty: true
          # resources:
          #   requests:
          #     memory: 1G
          #     cpu: 1
          env:
            {{- if .Values.debug }}
            - name: FLASK_DEBUG
              value: "1"
            {{- end }}
            - name: DASK_SCHEDULER_ADDRESS
              value: {{ template "simsvc.fullname" . }}-scheduler:8786
            - name: WORK_DIR
              value: {{ if .Values.work.storageClass -}} "/work"
              {{- else -}} "" {{- end }}
            - name: SIMSVC_ROOT
              value: /{{ .Release.Name }}/
            {{- if .Values.openShift }}
            - name: HTPASSWD_FILE
              value: "/htpasswd/auth"
            {{- end }}
          volumeMounts:
            {{- if .Values.work.storageClass }}
            - mountPath: "/work"
              name: work
            {{- end }}
            {{- if .Values.db.storageClass }}
            - mountPath: "/db"
              name: db
            {{- end }}
            {{- if .Values.openShift }}
            - mountPath: "/htpasswd"
              name: htpasswd
            {{- end }}
      volumes:
        {{- if .Values.work.storageClass }}
        - name: work
          persistentVolumeClaim:
            claimName: {{ template "simsvc.fullname" . }}-work
        {{- end }}
        {{- if .Values.db.storageClass }}
        - name: db
          persistentVolumeClaim:
            claimName: {{ template "simsvc.fullname" . }}-db
        {{- end }}
        {{- if .Values.openShift }}
        - name: htpasswd
          secret:
            secretName: {{ .Values.server.pwsecret }}
        {{- end }}
      {{- if .Values.server.spec }}
{{ toYaml .Values.server.spec | indent 6 }}
      {{- end }}
