{{ if .Values.work.storageClass -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "simsvc.fullname" . }}-work
spec:
  accessModes:
    - ReadWriteMany
  {{ if ne .Values.work.storageClass "default" -}}
  storageClassName: {{ .Values.work.storageClass }}
  {{ end -}}
  resources:
    requests:
      storage: {{ .Values.work.size }}
{{ end -}}
